package marpetplace.api.domain;

public enum Raca {
    VIRA_LATA,
    LABRADOR_RETRIEVER,
    BULDOGUE_FRANCÊS,
    PASTOR_ALEMÃO,
    GOLDEN_RETRIEVER,
    BULDOGUE_INGLÊS,
    POODLE,
    BEAGLE,
    ROTTWEILER,
    YORKSHIRE_TERRIER,
    PERSA,
    SIAMES,
    MAINE_COON,
    RAGDOLL,
    BENGAL,
    SPHYNX,
    BRITISH_SHORTHAIR,
    SCOTTISH_FOLD,
    SIAMESE,
    ABYSSINIAN,
    OUTRA
}
